# Generated by Django 6.0.7 on 2026-07-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_until', models.DateTimeField(verbose_name='Действителен до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', '💳 Картой онлайн'), ('cash', '📦 При получении'), ('installment', '📱 Рассрочка')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
