# Generated by Django 6.0.7 on 2026-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_promocode_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Срок (MM/YY)'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Номер карты'),
        ),
        migrations.AddField(
            model_name='order',
            name='installment_months',
            field=models.IntegerField(blank=True, choices=[(3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев'), (24, '24 месяца')], null=True, verbose_name='Срок рассрочки (месяцев)'),
        ),
    ]
