# Generated by Django 6.0.7 on 2026-07-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_card_expiry_order_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', '💳 Картой онлайн'), ('cash', '📦 При получении заказа'), ('installment', '📱 Рассрочка')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
