# Generated by Django 6.0.7 on 2026-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_color_alter_order_payment_method_cartitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', '💳 Картой онлайн'), ('cash', '📦 При получении заказа'), ('installment', '📱 Рассрочка')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
