# Generated by Django 6.0.7 on 2026-07-31 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Размер')),
                ('category_type', models.CharField(choices=[('clothing', 'Одежда'), ('shoes', 'Обувь'), ('furniture', 'Мебель'), ('universal', 'Универсальный')], default='universal', max_length=20, verbose_name='Тип категории')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', '💳 Картой онлайн'), ('cash', '📦 При получении'), ('installment', '📱 Рассрочка')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='shop.size', verbose_name='Доступные размеры'),
        ),
    ]
