# Generated by Django 6.0.7 on 2026-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ В обработке'), ('confirmed', '✅ Подтверждён'), ('shipped', '🚚 Отправлен'), ('delivered', '📦 Доставлен'), ('cancelled', '❌ Отменён')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
